### ISSUE TITLE
Catchall

### ISSUE THREAD

**Issue by hellowtf01** [0xNev/Disocord-Token-Generator#1]
Hy,what it's catchall?

**Comment by n3-v** [comment]
https://www.namecheap.com/help-center/knowledgebase/article.aspx/310/2214/how-to-set-up-a-catchall-wildcard-email-address/ This should help you out

**Comment by hellowtf01** [comment]
Got it,can you implement sms verification https://5sim.net/ ? And do you have a Discord/telegram contact ?

**Comment by n3-v** [comment]
possibly, snevou#6303
