### ISSUE TITLE
,

### ISSUE THREAD

**Issue by nighttsss** [0xNev/Disocord-Token-Generator#12]
ValueError: not enough values to unpack (expected 4, got 2)

**Comment by n3-v** [comment]
does it give a line number?

**Comment by nighttsss** [comment]
Traceback (most recent call last):
  main.py", line 192, in <module>
    run.start(i)
  main.py", line 164, in start
    proxies = gen.proxy()
main.py", line 147, in proxy
    ip,port,user,passw = f.split(':')
ValueError: not enough values to unpack (expected 4, got 2)

**Comment by damkavz** [comment]
If u don't got any proxies put 
proxy = False 
in the line 137 👍

**Comment by nighttsss** [comment]
but i got
