### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jarvn** [0xNev/Disocord-Token-Generator#2]
Does this create unlocked accs?

**Comment by hellowtf01** [comment]
Can you add 5sim.net for verify ?

**Comment by n3-v** [comment]
just pushed test.py lmk how it works. Should unlock accounts

**Comment by n3-v** [comment]
(5sim support)

**Comment by DaddyShank** [comment]
does it work?

**Comment by hellowtf01** [comment]
i will try now 5sim

**Comment by hellowtf01** [comment]
line 151
    "phone":phone
    ^^^^^^^

**Comment by DaddyShank** [comment]
yea got same error lol

**Comment by n3-v** [comment]
forgot comma in json header one sec

**Comment by hellowtf01** [comment]
waiting :)

**Comment by hellowtf01** [comment]
fivesim = " " what need to input the site ?

**Comment by DaddyShank** [comment]
does the one without sim works"?

**Comment by hellowtf01** [comment]
> does the one without sim works"?

Yes creata disccourd accounts but get instant locked need phone verify.

**Comment by DaddyShank** [comment]
> > does the one without sim works"?
> 
> Yes creata disccourd accounts but get instant locked need phone verify.

where do u get ur proxy format from dude

**Comment by hellowtf01** [comment]
> > > does the one without sim works"?
> > 
> > 
> > Yes creata disccourd accounts but get instant locked need phone verify.
> 
> where do u get ur proxy format from dude

I use Paid proxy

**Comment by DaddyShank** [comment]
wh

> > > > does the one without sim works"?
> > > 
> > > 
> > > Yes creata disccourd accounts but get instant locked need phone verify.
> > 
> > 
> > where do u get ur proxy format from dude
> 
> I use Paid proxy

what proxy

**Comment by hellowtf01** [comment]
rainproxy.io here proxy

**Comment by DaddyShank** [comment]
> rainproxy.io here proxy

whats ur cord

**Comment by hellowtf01** [comment]
> > rainproxy.io here proxy
> 
> whats ur cord

what ?

**Comment by DaddyShank** [comment]
> 

u got discord?

**Comment by hellowtf01** [comment]
> > 
> 
> u got discord?

OnlyF#8545

**Comment by DaddyShank** [comment]
> > > 
> > 
> > 
> > u got discord?
> 
> OnlyF#8545

added

**Comment by n3-v** [comment]
can't get 5sim to work rn, will work on this weekend.

**Comment by n3-v** [comment]
> fivesim = " " what need to input the site ?

its the for the 5sim api key(https://5sim.net/settings/security), will update the readme once updated and working to help clarify

**Comment by hellowtf01** [comment]
> can't get 5sim to work rn, will work on this weekend.

Will be great !

**Comment by hellowtf01** [comment]
> > fivesim = " " what need to input the site ?
> 
> its the for the 5sim api key(https://5sim.net/settings/security), will update the readme once updated and working to help clarify

Can i get your Discord,i have something interested to show you about generator :)

**Comment by n3-v** [comment]
snevou#6303
