### ISSUE TITLE
accounts disabled after email verify

### ISSUE THREAD

**Issue by Vamp999** [0xNev/Disocord-Token-Generator#23]
![image](https://user-images.githubusercontent.com/98104219/191996708-e3e982d9-6525-4c64-a13c-dae854906443.png)

How to fix this?

**Comment by n3-v** [comment]
The accounts get flagged with this gen most likely because of the hcaptcha bypass.

**Comment by Vamp999** [comment]
> The accounts get flagged with this gen most likely because of the hcaptcha bypass.

Ok but is there anything that can fix it?
