### ISSUE TITLE
Where can i get proxies??

### ISSUE THREAD

**Issue by iamsamir090** [0xNev/Disocord-Token-Generator#5]
Where can i get proxies with the format you used ??

**Comment by 0xNev** [comment]
basically anywhere that uses User:pass, the ones i tested were webshare proxies

**Comment by iamsamir090** [comment]
Hey thnx for replying...after using webshare proxies i am getting this  “ token: rate limited ! “
![D57F2AA6-6327-435F-AE73-2FAAC978622C](https://user-images.githubusercontent.com/81808632/155876066-1bb57bfa-52f8-4c40-8924-ecba92fe9fbe.png)

**Comment by 0xNev** [comment]
I think all most webshare proxies are banned since the proxies they give out the same proxies
